

security:
  basic:
    enabled: false
zuul:
  addHostHeader: true
  routes:
     producer:
      service-id: producer
      path: /producer/**
     customer:
      service-id: customer
      path: /customer/**
