# 全局配置
spring:
  profiles:
    active: @project.env@
  application:
    name: zuul
server:
  port: 8092
  context-path: /apps

---
# 生产环境配置 prod

spring:
  profiles: prod
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
security:
  basic:
    enabled: false
zuul:
  addHostHeader: true
  routes:


---
# 开发环境配置

console-available: true
spring:
  profiles: dev
  output:
     ansi:
       enabled: ALWAYS
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
security:
  basic:
    enabled: false
zuul:
  addHostHeader: true
  routes:
     producer:
      service-id: producer
      path: /producer/**
     customer:
      service-id: customer
      path: /customer/**
