
console-available: true
spring:
  output:
     ansi:
       enabled: ALWAYS
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: @db.url@
    username: @db.username@
    password: @db.password@
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: @db.initialSize@ # 初始化大小
    minIdle: @db.minIdle@
    maxActive: @db.maxActive@
    maxWait: @db.maxWait@ # 配置获取连接等待超时的时间
    timeBetweenEvictionRunsMillis: @db.timeBetweenEvictionRunsMillis@ # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    minEvictableIdleTimeMillis: @db.minEvictableIdleTimeMillis@   # 配置一个连接在池中最小生存的时间，单位是毫秒
    validationQuery: @db.validationQuery@
    testWhileIdle: @db.testWhileIdle@
    testOnBorrow: @db.testOnBorrow@
    testOnReturn: @db.testOnReturn@
    poolPreparedStatements: @db.poolPreparedStatements@ # 打开PSCache，并且指定每个连接上PSCache的大小
    maxPoolPreparedStatementPerConnectionSize: @db.maxPoolPreparedStatementPerConnectionSize@
    filters: @db.filters@
    connectionProperties: @db.connectionProperties@
server:
  context-path: /api
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true



