server:
  port: 8761
spring:
  application:
    name: erueak
  profiles:
    active: @project.env@
eureka:
  client:
    #是否注册到Eureka中
    registerWithEureka: false
    #此客户端是否获取eureka服务器注册表上的注册信息
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  