spring:
  application:
    name: erueak
  profiles:
    active: @project.env@

---
# 开发环境配置 dev

server:
  port: 8761
spring:
  profiles: dev
  output:
     ansi:
       enabled: ALWAYS
eureka:
  client:
     #是否注册到Eureka中
        registerWithEureka: false
        #此客户端是否获取eureka服务器注册表上的注册信息
        fetchRegistry: false
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
---
# 生产环境配置 prod
server:
  port: 8762
spring:
  profiles: prod
  output:
     ansi:
       enabled: ALWAYS
eureka:
  client:
        serviceUrl:
          defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
