# 全局配置:
server:
  port: 8081
spring:
  application:
        name: producer
  profiles:
        active: @project.env@
  cloud:
    config:
      #分支
      label: master
      #版本 dev--prod
      profile: @project.env@
      #配合中心url
      uri: http://localhost:8888/
      name: erueak,dataSource





